### ISSUE TITLE
Impressive work.

### ISSUE THREAD

**Issue by FarahZaqout** [aminalakhsham/first-project-for-code-academy#19]
30 commits for your first project on GitHub. That is very impressive.

A few things you missed are:
- You shouldn't use tagnames to apply style. You need to always give a class and use it to add style.
- Input fields should always have labels for them.
- close the issue after it's done.

There are also a few things with code style such as space and indentations, but that's something that will fix itself over time.

This is very good.

**Comment by yahyaHB** [comment]
I want to add something if you may:
 - Try to use more comfy colors
 - Same goes to the fonts
 - The `team members` cards have too much white empty space, sharp edges _which is hard for the eyes_

The work is really impressive like Farah said
