### ISSUE TITLE
as a user I want to see the skills of each team member

### ISSUE THREAD

**Issue by aminalakhsham** [aminalakhsham/first-project-for-code-academy#2]
### **Prepare a profile that contains:-**
 the **skills** of each person in the team with beautiful and attractive **images**

**Comment by FarahZaqout** [comment]
user stories are supposed to describe an interaction between the user and the website. 

```as a user I want to see the skills of each team member```

**Comment by FarahZaqout** [comment]
also if you start your line with * [ ] ```some text```

* [ ] the text will have a checkbox.

**Comment by aminalakhsham** [comment]
* [] amin
