### ISSUE TITLE
add sections & style sections

### ISSUE THREAD

**Issue by aminalakhsham** [aminalakhsham/first-project-for-code-academy#4]
### **add sections**
1. first section for team name and beautiful background .
2. second section have team images , and Name , something interest about everybody .
3. third section team skills 
4. forth section contact (Email, name, message and submit button)

### **style sections**
make it beautiful and easy to read , show every section fill the window

**Comment by FarahZaqout** [comment]
how does a user interact with navbar? It allows the user to go anywhere on the website easily.
think of a user story format for this interaction.
